In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [5]:
print(a)

[1 2 3 4 5]


In [6]:
a.shape  # shape means dimensionsof array returns a tuple n dimensional array

(5,)

In [9]:
b = np.array([[1],[2],[3],[4],[5]])

In [10]:
b.shape

(5, 1)

In [11]:
b[0][0]

1

In [15]:
b[3][0]

4

In [16]:
c = np.array([[1,2,3],[4,5,6]])

In [17]:
c.shape

(2, 3)

In [25]:
c[1][0]

4

In [31]:
# Create zeros,ones,custom array
a = np.zeros((3,3))
b = np.ones((2,3))
c = np.full((3,2),5)

In [36]:
a



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
c

array([[5, 5],
       [5, 5],
       [5, 5]])

In [39]:
# Indentify Matrix - Size / Squared matrix

In [41]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
#Random Mtrix

In [43]:
randomM = np.random.random((2,3))

In [44]:
randomM

array([[0.58225022, 0.94033659, 0.10723325],
       [0.80763103, 0.51746312, 0.7629643 ]])

In [46]:
print(randomM[:,1])  # For All Rows

[0.94033659 0.51746312]


In [52]:
randomM[:,1:3] = 1
randomM


array([[0.58225022, 1.        , 1.        ],
       [0.80763103, 1.        , 1.        ]])

In [71]:
z = np.zeros((3,3))

In [72]:
z[1,1:] = 5

In [73]:
z[:,-1] = 7 

In [74]:
z

array([[0., 0., 7.],
       [0., 5., 7.],
       [0., 0., 7.]])

In [75]:
z.dtype

dtype('float64')

In [76]:
# mathematical operations

In [83]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,4]])
print(x+y)
print(np.add(x,y))
np.subtract(x,y)

[[ 6  8]
 [10  8]]
[[ 6  8]
 [10  8]]


array([[-4, -4],
       [-4,  0]])

In [84]:
print(x*y)

[[ 5 12]
 [21 16]]


In [85]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 16]])

In [86]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 1.        ]])

In [87]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [88]:
# Matrix Multiplication and  Dot Products

In [89]:
x

array([[1, 2],
       [3, 4]])

In [90]:
y

array([[5, 6],
       [7, 4]])

In [92]:
print(x.dot(y))

[[19 14]
 [43 34]]


In [93]:
np.dot(x,y)

array([[19, 14],
       [43, 34]])

In [94]:
# Multiplication of vectors

In [129]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
a.dot(b)

30

In [130]:
print(sum(a))

10


In [131]:
np.sum(a)

10

In [132]:
np.sum(x,axis = 0)   # axis can be 1 or 0 hor or vertical irrespective

array([4, 6])

In [133]:
# Stack of Arrays

In [134]:
a
b = b**2

In [135]:
a

array([1, 2, 3, 4])

In [136]:
b

array([ 1,  4,  9, 16], dtype=int32)

In [137]:
np.stack((a,b),axis = 1) # becomes 1 column and 0 rows 

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [138]:
np.stack((a,b),axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [141]:
a = a.reshape((4,2))

ValueError: cannot reshape array of size 4 into shape (4,2)

In [142]:
a

array([1, 2, 3, 4])

# Numpy Random Modues

In [146]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
import random as rd

In [150]:
np.random.shuffle(x)

In [152]:
x

array([0, 7, 4, 8, 1, 3, 6, 9, 5, 2])

In [160]:
# Returns value from a standard Norml Distribution
a = np.random.randn(2,3)

In [161]:
a

array([[ 0.85040008, -1.63359443, -0.73361171],
       [ 0.93238292,  0.7038793 , -0.59572704]])

In [162]:
a = np.random.randint(5,10,3) # in range 5 to 10 3 digits

In [163]:
a

array([9, 6, 8])

In [167]:
ele = np.random.choice([1,2,4,3,5,7,3,8])

In [168]:
ele

2

In [169]:
np.random.seed(1)  # Important

# Many Mathematical and Statistical Functions



In [170]:
a = np.array([[1,2,3,4],[5,6,7,8]])
np.min(a)

1

In [172]:
np.min(a,axis = 1)  # wahi row col ka chod

array([1, 5])

In [173]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
m

3.0

In [175]:
np.mean(a)

4.5

In [176]:
c = np.array([1,5,4,2,0])

In [177]:
np.median(c)

2.0

In [178]:
np.mean(c)

2.4

In [179]:
# Weights
wts = np.array([1,2,3,4,5])
print(np.average(c,weights = wts))

2.066666666666667


In [181]:
# Standard Deviation  which is signma underroot 1/N * summation of ele 

In [182]:
# Variance = sigma ^ 2

In [184]:
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))

In [185]:
myStd

1.854723699099141

In [186]:
dev = np.std(c)

In [187]:
dev

1.854723699099141

In [188]:
myStd**2

3.440000000000001

In [190]:
np.var(c)

3.4400000000000004